#!/usr/bin/expect

eval spawn ssh -p 2222 -t root@localhost
set prompt ":|#|\\\$"
interact -o -nobuffer -re $prompt return
send "mdb\r"
interact -o -nobuffer -re $prompt return
send "zlogin 7f3ba160-047c-4557-9e87-8157db23f205\r"
interact -o -nobuffer -re $prompt return
expect "\[root@dev-1 ~\]#"
send "rm -fr /root/*\r"
interact -o -nobuffer -re $prompt return


