#!/usr/bin/expect
set arg1 [lindex $argv 0]
set arg2 [lindex $argv 1]

eval spawn ssh -p 2222 -t root@localhost
set prompt ":|#|\\\$"
interact -o -nobuffer -re $prompt return
send "mdb\r"
interact -o -nobuffer -re $prompt return
send "zlogin 7f3ba160-047c-4557-9e87-8157db23f205 mdb $arg1 $arg2\r"
interact
